name: "Hello World"
description: "greet someone and record them time"
inputs:
  who-to-greet: id
  description: "who to greet"
  required: true
  default: "World"
outputs:
  time: id
  description: "the time we greeted you"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}
